import { Nunito } from "next/font/google";

const nunito = Nunito({
    weight: ['300','400', '500'],
    style: ['normal'],
    subsets: ['latin'],
})

export const metadata = {
    title: "Proyecto 2",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={nunito.className}>
                {children}
            </body>
        </html>
    );
}
