import NavbarAdmin from "../../components/navbarAdmin";

export const metadata = {
    title: "Admin",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
    return(
        <>
        <NavbarAdmin />
        {children}
        </>
    );
}